@startuml "initiate transaction to another player"

actor Admin

Activate Admin
Activate System

ref over Player, System : start game
activate Player

Admin -> System : click initiate transaction
System -> Admin : show transaction initiation form
Admin -> System : specify the amount and reciver player and confirme

System -> System : add the moeny to the reciver player
System -> Player : notify all the players

@enduml
