@startuml

actor Player

Activate Player
Activate FrontEnd

ref over Player, FrontEnd, BackEnd, DataBase : join game

actor Admin
Activate Admin
ref over Admin, FrontEnd, BackEnd, DataBase : start game usecase

Player -> FrontEnd : click initiate transaction button
FrontEnd -> Player : show forum
Player -> FrontEnd : fill forum
FrontEnd -> BackEnd : post forum(game, player, reciver, amount)
Activate BackEnd

BackEnd -> DataBase : add request to transactions table with status waiting)
Activate DataBase
DataBase -> BackEnd : confirme
deactivate DataBase

BackEnd -> FrontEnd : confirme

ref over Admin, BackEnd, DataBase : confirme/refuse transaction

FrontEnd -> BackEnd : get status
BackEnd -> DataBase : check game status if not ended yet/started, 
activate DataBase

DataBase -> BackEnd : confirme
deactivate DataBase

BackEnd -> DataBase : check player status isBankerypt(player)
activate DataBase

DataBase -> BackEnd : confirme
deactivate DataBase

BackEnd -> DataBase : get player reserve (player)
activate DataBase

DataBase -> BackEnd : response with data(reserve)
deactivate DataBase

BackEnd -> FrontEnd : status(Data)
FrontEnd -> Player : show new scene



@enduml
