@startuml
 
actor Guest

Activate Guest
Activate GuestFrontEnd
Activate BackEnd
Activate dataBase
Activate Admin
 
ref over Guest,GuestFrontEnd, BackEnd, dataBase : see available games usecase
deactivate BackEnd
deactivate dataBase
Guest -> GuestFrontEnd : choose a game from the list
GuestFrontEnd -> BackEnd : check Game(game)
Activate BackEnd
BackEnd -> dataBase : get game max players()
Activate dataBase
dataBase -> BackEnd : max players
deactivate dataBase
BackEnd -> BackEnd : calculate if there is room
BackEnd -> dataBase : add player to game(player, game)
Activate dataBase
dataBase -> BackEnd : list of players
deactivate dataBase
BackEnd -> GuestFrontEnd : players list

GuestFrontEnd -> Guest : send to the waiting room

@enduml
