@startuml

actor Guest

Activate Guest
Activate System

Guest ->  System : Host new game
System -> System : create new game
System -> System : new game waiting room

loop intel start or end game usecases are choosen
    System -> System : refresh players list
    System -> Guest : show players list
end

@enduml
