@@startuml "Monopoly guest usecase diagram"

left to right direction


actor Guest as g

package GuestUseCases {

usecase "host new game" as hg
usecase "see available games" as sg
usecase "join a game as player" as jg
usecase "join a game as viewer" as vg

}

g --> hg
g --> sg
g --> jg
g --> vg

@@enduml
