@startuml "Monopoly admin usecase diagram"

left to right direction
skinparam style strictuml

actor "game hoster/admin" as ad

package oneGame {

    package players {
        usecase "kick and bane player out" as kp
	usecase "unbane player" as ubp
    }

    package game {
        usecase "start game" as strtg
        usecase "end game" as eg
    }

    package transactions {
        package actions {
            usecase "see transactions requests" as st
            usecase "accept/refuse transactions" as at
            usecase "initiate transaction from bank to player" as itgp
        }
        package history {
            usecase "see history of transaction of one player" as seeplrtr
            usecase "see history of transaction of bank" as seebnktr
            usecase "see history of transaction of all player and bank" as seealltr
        }
    }
}

ad --> kp
ad --> ubp

ad --> strtg
ad --> eg

ad --> st
ad --> at
ad --> itgp

ad --> seeplrtr
ad --> seebnktr

ad --> seealltr

@enduml
