@startuml "initiate transaction to a player"

actor Admin

Activate Admin
Activate FrontEnd

ref over Admin, FrontEnd, BackEnd, Database: start game
Activate player

Admin ->  FrontEnd : click initiate transaction
FrontEnd -> Admin : show transaction initiation form
Admin -> FrontEnd : specify the amount and reciver player and confirme

FrontEnd -> BackEnd : initiate transaction(reciver player, amount)
activate BackEnd

BackEnd -> Database : add a transaction (amount, sender=bank, reciver, status=approved)
Activate Database

Database -> BackEnd : confirme
deactivate Database

BackEnd -> Database : add a amount of money to player(amount, player)
Activate Database

Database -> BackEnd : confirme
deactivate Database

BackEnd -> FrontEnd : confrime
deactivate BackEnd

FrontEnd -> Admin : show success

@enduml
