@startuml

actor Admin

Activate Admin
Activate FrontEnd

ref over Admin, FrontEnd, BackEnd, Database : host game usecase

Admin ->  FrontEnd : click bane player
FrontEnd -> BackEnd : bane player (player)
Activate BackEnd

BackEnd -> Database : set status as banned in the player table
Activate Database

Database -> BackEnd : confirme
deactivate Database

BackEnd -> FrontEnd : confirme
deactivate BackEnd

loop intel start or end game usecases are choosen

    FrontEnd -> BackEnd : get players list
    Activate BackEnd

    BackEnd -> Database : get list of players
    Activate Database

    Database -> BackEnd : list of game players
    deactivate Database

    BackEnd -> FrontEnd : list of game players
    deactivate BackEnd

    FrontEnd -> Admin : show players list

end

@enduml
