@startuml see players joining requests

actor Admin

activate Admin
activate FrontEnd

ref over Admin, FrontEnd: host new game usecase

Admin -> FrontEnd : click on show request button
FrontEnd -> Backend: get joining request

activate Backend

Backend -> database : request list of requests

activate database

database -> Backend : response with list of joining reuqests for the specified game
deactivate database

Backend -> FrontEnd : list of requests
deactivate Backend

FrontEnd -> Admin : show list of request with accept and refuse buttons

@enduml