@startuml

actor Admin

Activate Admin
Activate FrontEnd

ref over Admin, FrontEnd, BackEnd, Database : kick players out usecase

Admin ->  FrontEnd : banned players list
FrontEnd -> BackEnd : get banned players(game)
Activate BackEnd

BackEnd -> Database : get players list with status banned(game)
Activate Database

Database -> BackEnd : list of banned players
deactivate Database

BackEnd -> FrontEnd : banned players list
deactivate BackEnd

FrontEnd -> Admin : show list of banned players

Admin -> FrontEnd : click unban on a specific banned player
FrontEnd -> BackEnd : unbanne player (player)
Activate BackEnd

BackEnd -> Database : change player isBanned status to false(player, game)
Activate Database

Database -> BackEnd : confirme
deactivate Database

BackEnd -> FrontEnd : confirme
deactivate BackEnd


loop intel start or end game usecases are choosen

    FrontEnd -> BackEnd : get players list
    Activate BackEnd

    BackEnd -> Database : get players list in the game
    Activate Database

    Database -> BackEnd : list of game players
    deactivate Database

    BackEnd -> FrontEnd : list of game players
    deactivate BackEnd

    FrontEnd -> Admin : show players list

end

@enduml
